---
- hosts: all
  become: yes
  tasks:
    - name: Include variables
      include_vars: vars.yaml

    - name: Update Repository Cache
      command: apt update -y

    - name: Upgrade Packages
      command: apt upgrade -y

    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Start HAProxy
      service:
        name: haproxy
        state: started
        enabled: yes

    - name: Add user
      user:
        name: "{{ user }}"
        state: present
        shell: /bin/bash
        password: "{{ password }}"
        groups: sudo
        append: yes

    - name: Append HAProxy configuration
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        block: |
          frontend http_front
              bind *:80
              default_backend http_back

          backend http_back
              balance roundrobin
              server nginx1 192.168.100.22:80 check
              server nginx2 192.168.100.23:80 check
        marker: "# {mark} Managed By Ansible"
        create: yes

    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

    - name: Make .ssh directory
      file:
        path: /home/{{ user }}/.ssh/
        state: directory

    - name: Append public key to authorized_keys
      copy:
        dest: "/home/{{ user }}/.ssh/authorized_keys"
        content: "{{ lookup('file', '/home/alex/.ssh/alex_key.pub') }}"
        mode: '0600'
        owner: "{{ user }}"
        group: "{{ user }}"
        backup: yes